<?php
/** @var \Magento\Framework\View\Element\AbstractBlock $block */

$staticFilePath = $block->getViewFileUrl('KingfisherDirect_CookieConsent::js/cookieconsent-init.js');
$cssPath = $block->getViewFileUrl('KingfisherDirect_CookieConsent::css/cookieconsent.css');
?>

<link rel='preload' href='<?= /** @noEscape */ $cssPath; ?>' as='style' onload='this.onload=null;this.rel="stylesheet"' fetchpriority="low" />
<script type="module" fetchpriority="low" src="<?= /** @noEscape */ $staticFilePath; ?>"></script>
